### ISSUE TITLE
Where to get an account, the token

### ISSUE THREAD

**Issue by jiangzy26** [natverse/rcatmaid#175]
Hi,
I want to use rcatmaid in my research, however, I have no idea where to get an account and the token, could you share the place, I want to apply one.
Thank you very much for your help.

All the best,
Zhiyong Jiang

**Comment by jefferis** [comment]
Dear Zhiyong Jiang, thanks for your interest. There is no single account and token – it depends on the dataset that you are hoping to use. If you already have access to a closed access catmaid server, you can get an access token from the catmaid web interface (see http://catmaid.github.io/dev/api.html#api-token).

If not, then you can access some public servers like those from [VFB](https://www.virtualflybrain.org/) without using a token. The [`vfbcatmaid()`](https://natverse.org/rcatmaid/reference/vfbcatmaid.html) function provides a convenient way to connect to those servers.

```
library(catmaid)
fafb=vfbcatmaid('fafb')
fafbal=catmaid_get_annotationlist(conn = fafb)
# find annotations that define published papers
library(dplyr)
fafbal$annotations %>%
  filter(grepl("^Paper", name))
# get the neurons associated with Wang et al Nature 2020 
wang2020a=read.neurons.catmaid('Paper: Wang et al 2020a')
plot(wang2020a, WithNodes=F)

# 3d plot
library(elmr)
plot3d(wang2020a)
plot3d(FAFB)
```
<img width="855" alt="image" src="https://user-images.githubusercontent.com/23763/184320190-ee539a95-ae8a-481e-aa68-1334b98ed38c.png">
