### ISSUE TITLE
How to read skeletons of two neurons in a template?

### ISSUE THREAD

**Issue by shenpeng2022** [natverse/rcatmaid#176]
Hi!
  I want to read skeletons of two neurons by rcatmaid. Could you show me how to do that? For example: DA1 and aSP-g neurons.
Thanks for your help!

All the best,
Peng

**Comment by jefferis** [comment]
Dear Peng, If you want advice on how to use the natverse, please ask questions on the google group https://groups.google.com/g/nat-user. In this case you will need to say what dataset you want these neurons to come from. Best wishes, Greg Jefferis.
